version: "3"

services:
  mysql-master:
      image: mysql:8.0
      container_name: mysql-master
      networks:
        - mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app
      volumes:
        - ./mysql/master/my.cnf:/etc/mysql/my.cnf
        - ./mysql/master/data:/var/lib/mysql
        - ./mysql/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 3307:3306
      platform: linux/amd64

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    networks:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - ./mysql/slave/my.cnf:/etc/mysql/my.cnf
      - ./mysql/slave/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3308:3306
    depends_on:
      - mysql-master
    platform: linux/amd64

  wdk:
    image: jreesman1/wdk:latest-amd64
    container_name: wdk
    environment:
      kafkaURL: wdk-kafka-1:9093
      GRPC_HOST: wdk-server:9999
      DB_MASTER: mysql-master:3306
      DB_SLAVE: mysql-master:3306
      DB_USER: root
      DB_PWD: password
      DB_NAME: app
    ports: 
      - 3100:3100
    networks:
      - wdk
      - mysql
    depends_on:
      - wdk-server
    platform: linux/amd64

  wdk-server:
    image: jreesman1/wdk-server:latest-amd64
    container_name: wdk-server
    ports: 
      - 9999:9999
    networks:
      - wdk
    platform: linux/amd64


networks:
  wdk:
  db:
  mysql:

