# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watchdog.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewatchdog.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"!\n\x10SentimentRequest\x12\r\n\x05tweet\x18\x01 \x01(\t\"%\n\x11SentimentResponse\x12\x10\n\x08polarity\x18\x01 \x01(\x02\",\n\x0cQuoteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06period\x18\x02 \x01(\t\"@\n\x05Quote\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05price\x18\x02 \x01(\x02\"*\n\rQuoteResponse\x12\x19\n\x06quotes\x18\x01 \x03(\x0b\x32\t.pb.Quote2D\n\tSentiment\x12\x37\n\x06\x44\x65tect\x12\x14.pb.SentimentRequest\x1a\x15.pb.SentimentResponse\"\x00\x32\x39\n\x06Quotes\x12/\n\x06\x44\x65tect\x12\x10.pb.QuoteRequest\x1a\x11.pb.QuoteResponse\"\x00\x42)Z\'github.com/jonreesman/watch-dog/grpc/pbb\x06proto3')



_SENTIMENTREQUEST = DESCRIPTOR.message_types_by_name['SentimentRequest']
_SENTIMENTRESPONSE = DESCRIPTOR.message_types_by_name['SentimentResponse']
_QUOTEREQUEST = DESCRIPTOR.message_types_by_name['QuoteRequest']
_QUOTE = DESCRIPTOR.message_types_by_name['Quote']
_QUOTERESPONSE = DESCRIPTOR.message_types_by_name['QuoteResponse']
SentimentRequest = _reflection.GeneratedProtocolMessageType('SentimentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENTIMENTREQUEST,
  '__module__' : 'watchdog_pb2'
  # @@protoc_insertion_point(class_scope:pb.SentimentRequest)
  })
_sym_db.RegisterMessage(SentimentRequest)

SentimentResponse = _reflection.GeneratedProtocolMessageType('SentimentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENTIMENTRESPONSE,
  '__module__' : 'watchdog_pb2'
  # @@protoc_insertion_point(class_scope:pb.SentimentResponse)
  })
_sym_db.RegisterMessage(SentimentResponse)

QuoteRequest = _reflection.GeneratedProtocolMessageType('QuoteRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUOTEREQUEST,
  '__module__' : 'watchdog_pb2'
  # @@protoc_insertion_point(class_scope:pb.QuoteRequest)
  })
_sym_db.RegisterMessage(QuoteRequest)

Quote = _reflection.GeneratedProtocolMessageType('Quote', (_message.Message,), {
  'DESCRIPTOR' : _QUOTE,
  '__module__' : 'watchdog_pb2'
  # @@protoc_insertion_point(class_scope:pb.Quote)
  })
_sym_db.RegisterMessage(Quote)

QuoteResponse = _reflection.GeneratedProtocolMessageType('QuoteResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUOTERESPONSE,
  '__module__' : 'watchdog_pb2'
  # @@protoc_insertion_point(class_scope:pb.QuoteResponse)
  })
_sym_db.RegisterMessage(QuoteResponse)

_SENTIMENT = DESCRIPTOR.services_by_name['Sentiment']
_QUOTES = DESCRIPTOR.services_by_name['Quotes']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\'github.com/jonreesman/watch-dog/grpc/pb'
  _SENTIMENTREQUEST._serialized_start=55
  _SENTIMENTREQUEST._serialized_end=88
  _SENTIMENTRESPONSE._serialized_start=90
  _SENTIMENTRESPONSE._serialized_end=127
  _QUOTEREQUEST._serialized_start=129
  _QUOTEREQUEST._serialized_end=173
  _QUOTE._serialized_start=175
  _QUOTE._serialized_end=239
  _QUOTERESPONSE._serialized_start=241
  _QUOTERESPONSE._serialized_end=283
  _SENTIMENT._serialized_start=285
  _SENTIMENT._serialized_end=353
  _QUOTES._serialized_start=355
  _QUOTES._serialized_end=412
# @@protoc_insertion_point(module_scope)
